### ISSUE TITLE
Able to implement this with react-router v4?

### ISSUE THREAD

**Issue by aagentah** [justinjung04/universal-boilerplate#5]
This repo has been really useful for me, would be cool if it used some more up-to date packages :) Peace!

**Comment by athivvat** [comment]
@danjonescidtrix I will fork to implement react-router v4

**Comment by aagentah** [comment]
Life saver @athivvat

**Comment by GustavoHGS** [comment]
True life saver ;)

**Comment by danjonesdev** [comment]
@athivvat man, you ever get round to this?

**Comment by aagentah** [comment]
Anybody get around to doing this?
Thank you in advance!

**Comment by athivvat** [comment]
@danjonesdev @GustavoHGS I'm sorry for long time didn't respond. For this time, Maybe these project list help you for starting project
- [react-cool-starter](https://github.com/wellyshen/react-cool-starter)
- [The-Ultimate-Boilerplate](https://github.com/touqeerkhan11/The-Ultimate-Boilerplate)

However, If my work is done I will continue to fix this issue.

**Comment by aagentah** [comment]
@athivvat  If you could update to V4 I would really appreciate it, your boilerplate is one of the most practical one's I have come across - thank you in advance!

**Comment by justinjung04** [comment]
Sorry I hadn't got a chance to work on this for a while. I've updated react router to v4. Let me know if there's any bug!
