### ISSUE TITLE
not isomorphic in development mode

### ISSUE THREAD

**Issue by hackfaq** [justinjung04/universal-boilerplate#6]
if i use npm start app is not isomorphic, its client only =(

**Comment by athivvat** [comment]
@hackfaq If you need enable server rendering in development mode you can handle in middleware.js

**Comment by justinjung04** [comment]
You are right, this boilerplate isn't isomorphic in development mode. The boilerplate leverages react-hmre for css hot loading during dev. Once you build and run your app, that's when you see the app isomorphic.
